name: E2E autotests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "develop" ]
  workflow_dispatch:
  
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Autotests
    steps:
      - name: Start Selenoid Server
        run: |
          cd selenoid
          ./cm selenoid start --vnc
      - uses: actions/checkout@v1
      - name: Run tests
        env:
          SELENIUM_HUB_HOST: 'localhost'
        run: npm cit
      - name: Create Report
        run: npm run report:gen
      - uses: actions/upload-artifact@v1
        with:
            name: allure-report
            path: ./allure-report
      - name: Deploy Report
        env:
          SECRET: ${{ secrets.ALLURE_DEPLOY_S3_SECRET }}
          ACCESS_KEY: ${{ secrets.ALLURE_DEPLOY_S3_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $ACCESS_KEY
          aws configure set aws_secret_access_key $SECRET
          aws configure set region us-west-1
          aws s3 mv allure-report s3://hobbit-allure/reports/project/ --endpoint-url https://hb.bizmrg.com --recursive
