name: E2E autotests

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Директория проекта'
        required: true
        type: choice
        options: 
          - example
      browsers:
        description: 'На каких браузерах запустить тесты'
        required: true
        type: multi-choice
        options: 
          - chrome
          - firefox


jobs:
  tests:
    runs-on: ubuntu-latest
    name: Autotests
    env:
      PROJECT_NAME: ${{ github.event.inputs.project }}
      BROWSERS: ${{ github.event.inputs.browsers }}
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          npm ci
          SELENIUM="on" npm run test
          echo ${{ vars.ALLURE_ENDPOINT}}
      - name: Create Report
        run: npm run report:gen
      - uses: actions/upload-artifact@v1
        with:
            name: allure-report
            path: ./allure-report
      - name: Deploy Report
        env:
          SECRET: ${{ secrets.ALLURE_DEPLOY_S3_SECRET }}
          ACCESS_KEY: ${{ secrets.ALLURE_DEPLOY_S3_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $ACCESS_KEY
          aws configure set aws_secret_access_key $SECRET
          aws configure set region us-west-1
          export timestamp=$(date +%s)
          echo "ALLURE_PATH=$(echo hobbit-allure/reports/$PROJECT_NAME/${{ github.actor }}/$timestamp)" >> $GITHUB_ENV
          aws s3 mv allure-report s3://hobbit-allure/reports/$PROJECT_NAME/${{ github.actor }}/$timestamp/ --endpoint-url ${{ vars.ALLURE_ENDPOINT}} --recursive
      - name: Notify
        run: |
          echo URL TO ALLURE -- https://hb.bizmrg.com/$ALLURE_PATH/index.html
