name: E2E autotests

on:
  push:
  workflow_dispatch:
    inputs:
      includeTests:
        description: 'Тесты для запуска (сепаратор - запятая)'
        required: false
        default: ''
        type: string
      project:
        description: 'Директория проекта'
        required: true
        type: choice
        options: 
          - example

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Autotests
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          npm ci
          npm run test
      - name: Create Report
        run: npm run report:gen
      - uses: actions/upload-artifact@v1
        with:
            name: allure-report
            path: ./allure-report
      - name: Deploy Report
        env:
          SECRET: ${{ secrets.ALLURE_DEPLOY_S3_SECRET }}
          ACCESS_KEY: ${{ secrets.ALLURE_DEPLOY_S3_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $ACCESS_KEY
          aws configure set aws_secret_access_key $SECRET
          aws configure set region us-west-1
          export timestamp=$(date +%s)
          aws s3 mv allure-report s3://hobbit-allure/reports/${{ github.event.inputs.project }}/${{ github.actor }}/$timestamp/ --endpoint-url https://hb.bizmrg.com --recursive
