name: E2E autotests

on:
  workflow_dispatch:
  
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Autotests
    steps:
      - name: Start Selenoid Server
        uses: Xotabu4/selenoid-github-action@v2
      - uses: actions/checkout@v1
      - name: Run tests
        env:
          SELENIUM_HUB_HOST: 'localhost'
        run: |
          nvm use
          npm ci
          npm run wdio